### PR TITLE
#164666996 ft login

### PR DESCRIPTION
**Pull request by alexxsanya**
**What does this PR do?**

- Create the login page
- Create styles for the login page

**Description of Task to be completed?**
- Created the login page
- Created the styles for login page (login.css)

**How should this be manually tested?**

click here to view the changes [here](https://alexxsanya.github.io/EPIC-MAIL/UI/login.html)

@jennizalwango @Wabuluka @bekeplar @bisonlou  @JamesMudidi @kyakusahmed @Ivankivu @neelxie

### CODE REVIEW

**Comment by Wabuluka** [comment]
This absolutely awesome, the page is responsive, just make sure all the broken links are removed

**Comment by neelxie** [comment]
Bro clean interface, but your placeholder says username yet the input
type is for emails??
Was expecting a sign up link somwhere.

**Comment by alexxsanya** [comment]
@neelxie & @Wabuluka  thanks. let me work on them

**Comment by jennizalwango** [comment]
nice description of your the PR

**Pull request merged**
